version: '3'
services:
  web:
    build: .
    ports:
      - "2368:2368"
    volumes:
      - ./app:/app/
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: mysql://andrew:admin@192.168.122.227:3306/keycloakdb
    command: flask run --host=0.0.0.0
  redis:
    image: redis


